spring.application.name=spring-ai-image

spring.ai.model.chat=anthropic
spring.ai.model.embedding=none
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.moderation=none

spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.chat.model=claude-haiku-4-5-20251001

spring.ai.openai.api-key=${OPENAI_API_KEY}
